##
## EPITECH PROJECT, 2020
## B-FUN-300-BDX-3-1-funPoolDay2-quentin.garcia
## File description:
## makefile
##

MAIN	=	DoOp.hs

NAME	=	doop

all:
	ghc -o $(NAME) $(MAIN)

clean:
	rm -f *.o
	rm -f *.hi

fclean:		clean
	rm -f $(NAME)

re: fclean all