##
## EPITECH PROJECT, 2021
## B-CNA-410-BDX-4-1-groundhog-quentin.garcia
## File description:
## Makefile
##

all:
	cp groundhog.py groundhog
	chmod 777 groundhog


clean:

fclean: clean
		rm groundhog

re: fclean all