/*
** EPITECH PROJECT, 2021
** B-PSU-402-BDX-4-1-strace-quentin.garcia
** File description:
** syscall_info
*/

#ifndef SYSCALL_INFO_H_
#define SYSCALL_INFO_H_

enum arg_type {
    INT,
    CHAR,
    CHAR_STAR,
    CHAR_STAR_S,
    DOUBLE,
    LONG,
    LONG_D,
    UNSIGNED,
    UNSIGNED_L,
    FLOAT,
    POINTER,
    POINTER_P,
    STRUCT,
    OFF
};

typedef struct syscall_s
{
    char *name;
    char arg1;
    char arg2;
    char arg3;
    char arg4;
    char arg5;
    char arg6;
    int arg_nbr;
} syscall_t;

static const syscall_t sys_arr[] =
{
    {"read", UNSIGNED, CHAR_STAR, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"write", UNSIGNED, CHAR_STAR, UNSIGNED,
    OFF, OFF, OFF,3},
    {"open", CHAR_STAR, INT, INT, OFF, OFF, OFF, 3},
    {"close", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"stat", CHAR_STAR, STRUCT, OFF,
    OFF,OFF, OFF, 2},
    {"fstat", UNSIGNED, STRUCT, OFF,
    OFF, OFF, OFF, 2},
    {"lstat", CHAR_STAR, STRUCT, OFF,
    OFF, OFF, OFF, 2},
    {"poll", STRUCT, UNSIGNED, LONG,
    OFF, OFF, OFF, 3},
    {"lseek", UNSIGNED, UNSIGNED, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"mmap", UNSIGNED_L, UNSIGNED_L, UNSIGNED_L,
    UNSIGNED_L, UNSIGNED_L, UNSIGNED_L, 6},
    {"mprotect", UNSIGNED_L, UNSIGNED, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"munmap", UNSIGNED_L, UNSIGNED, OFF,
    OFF, OFF, OFF, 2},
    {"brk", UNSIGNED_L, OFF,OFF,
    OFF, OFF, OFF, 1},
    {"rt_sigaction", INT, STRUCT, STRUCT,
    UNSIGNED, OFF, OFF, 4},
    {"rt_sigprocmask", INT, STRUCT, STRUCT,
    UNSIGNED, OFF, OFF, 4},
    {"rt_sigreturn", UNSIGNED, OFF, OFF,
    OFF, OFF,OFF, 1},
    {"ioctl", UNSIGNED, UNSIGNED, UNSIGNED_L,
    OFF, OFF, OFF, 3},
    {"pread64", UNSIGNED_L, CHAR_STAR, UNSIGNED,
    UNSIGNED, OFF, OFF, 4},
    {"pwrite64", UNSIGNED_L, CHAR_STAR, UNSIGNED,
    UNSIGNED, OFF, OFF, 4},
    {"readv", UNSIGNED_L, STRUCT, UNSIGNED_L,
    OFF, OFF, OFF,3},
    {"writev", UNSIGNED_L, STRUCT, UNSIGNED_L,
    OFF, OFF, OFF, 3},
    {"access", CHAR_STAR, INT, OFF,
    OFF, OFF, OFF, 2},
    {"pipe", INT, OFF,OFF,
    OFF, OFF, OFF, 1},
    {"select", INT, POINTER, OFF,
    OFF, OFF, OFF, 5},
    {"sched_yield", OFF, OFF, OFF,
    OFF, OFF,OFF, 0},
    {"mremap", UNSIGNED_L, UNSIGNED_L, UNSIGNED_L,
    UNSIGNED_L, UNSIGNED_L, OFF, 5},
    {"msync", UNSIGNED_L, UNSIGNED, INT,
    OFF, OFF, OFF, 3},
    {"mincore", UNSIGNED_L, UNSIGNED, CHAR_STAR,
    OFF, OFF, OFF, 3},
    {"madvise", UNSIGNED_L, UNSIGNED, INT,
    OFF, OFF, OFF, 3},
    {"shmget", UNSIGNED, UNSIGNED, INT,
    OFF, OFF, OFF, 3},
    {"shmat", INT, CHAR_STAR, INT,
    OFF, OFF, OFF, 3},
    {"shmctl", INT, INT, STRUCT,
    OFF, OFF, OFF, 3},
    {"dup", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"dup2", UNSIGNED, UNSIGNED , OFF,
    OFF, OFF, OFF, 2},
    {"pause", OFF, OFF, OFF,
    OFF, OFF, OFF, 0},
    {"nanosleep", STRUCT, STRUCT, OFF,
    OFF, OFF, OFF, 2},
    {"getitimer", INT, STRUCT, OFF,
    OFF, OFF, OFF, 2},
    {"alarm", INT, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"setitimer", INT, STRUCT, STRUCT,
    OFF, OFF, OFF, 3},
    {"getpid", OFF, OFF, OFF,
    OFF, OFF, OFF, 0},
    {"sendfile", INT, INT, UNSIGNED,
    POINTER, OFF, OFF, 4},
    {"socket", INT, INT, INT,
    OFF, OFF, OFF, 3},
    {"connect", INT, STRUCT, INT,
    OFF, OFF, OFF, 3},
    {"accept", INT, STRUCT, INT,
    OFF, OFF, OFF, 3},
    {"sendto", INT, POINTER, UNSIGNED,
    UNSIGNED, STRUCT, INT, 6},
    {"recvfrom", INT, POINTER, UNSIGNED,
    UNSIGNED, STRUCT, INT, 6},
    {"sendmsg", INT, STRUCT, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"recvmsg", INT, STRUCT, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"shutdown", INT, INT, OFF,
    OFF, OFF, OFF, 2},
    {"bind", INT, STRUCT, INT,
    OFF, OFF, OFF, 3},
    {"listen", INT, INT, OFF,
    OFF, OFF, OFF, 2},
    {"getsockname", INT, STRUCT, POINTER,
    OFF, OFF, OFF,3},
    {"getpeername", INT, STRUCT, INT,
    OFF, OFF, OFF, 3},
    {"socketpair", INT, INT , INT,
    POINTER, OFF, OFF, 4},
    {"setsockopt", INT, INT , INT,
    CHAR_STAR, INT, OFF,5},
    {"getsockopt", INT, INT, INT,
    CHAR_STAR, POINTER, OFF, 5},
    {"clone", UNSIGNED_L, UNSIGNED_L, POINTER,
    POINTER, OFF, OFF, 4},
    {"fork", OFF, OFF, OFF,
    OFF, OFF, OFF, 0},
    {"vfork", OFF, OFF, OFF, OFF, OFF, OFF, 0},
    {"execve", CHAR_STAR, CHAR_STAR_S, CHAR_STAR_S,
    OFF, OFF, OFF, 3},
    {"exit", INT, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"wait4", UNSIGNED, POINTER, INT, STRUCT,
    OFF, OFF, 4},
    {"kill", UNSIGNED, INT, OFF,
    OFF, OFF, OFF, 2},
    {"uname", STRUCT, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"semget", UNSIGNED, INT , INT,
    OFF, OFF, OFF, 3},
    {"semop", INT, STRUCT, UNSIGNED, OFF,
    OFF, OFF, 3},
    {"semctl", INT , INT, INT,
    POINTER, OFF, OFF, 4},
    {"shmdt", CHAR_STAR, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"msgget", UNSIGNED, INT, OFF,
    OFF, OFF, OFF, 2},
    {"msgsnd", INT, STRUCT, UNSIGNED,
    INT, OFF, OFF, 4},
    {"msgrcv", INT, STRUCT, UNSIGNED,
    LONG, INT, OFF, 5},
    {"msgctl", INT, INT, STRUCT,
    OFF, OFF, OFF, 3},
    {"fcntl", UNSIGNED, UNSIGNED, UNSIGNED_L,
    OFF, OFF, OFF, 3},
    {"flock", UNSIGNED, UNSIGNED, OFF,
    OFF, OFF, OFF, 2},
    {"fsync", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"fdatasync", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"truncate", CHAR_STAR, LONG, OFF,
    OFF, OFF, OFF, 2},
    {"ftruncate", UNSIGNED, UNSIGNED_L, OFF,
    OFF, OFF, OFF,2},
    {"getdents", UNSIGNED, STRUCT, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"getcwd", CHAR_STAR, UNSIGNED_L, OFF,
    OFF, OFF, OFF, 2},
    {"chdir", CHAR_STAR, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"fchdir", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"rename", CHAR_STAR, CHAR_STAR, OFF,
    OFF, OFF, OFF, 2},
    {"mkdir", CHAR_STAR, INT, OFF,
    OFF, OFF, OFF, 2},
    {"rmdir", CHAR_STAR, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"creat", CHAR_STAR, INT , OFF,
    OFF, OFF, OFF, 2},
    {"link", CHAR_STAR, CHAR_STAR, OFF,
    OFF, OFF, OFF, 2},
    {"unlink", CHAR_STAR, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"symlink", CHAR_STAR, CHAR_STAR, OFF,
    OFF, OFF, OFF, 2},
    {"readlink", CHAR_STAR, CHAR_STAR, INT,
    OFF, OFF, OFF, 3},
    {"chmod", CHAR_STAR, UNSIGNED, OFF,
    OFF, OFF, OFF, 2},
    {"fchmod", UNSIGNED, UNSIGNED, OFF, OFF,
    OFF, OFF, 2},
    {"chown", CHAR_STAR, UNSIGNED, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"fchown", UNSIGNED, UNSIGNED, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"lchown", CHAR_STAR, UNSIGNED, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"umask", INT, OFF, OFF, OFF,
    OFF, OFF, 1},
    {"gettimeofday", STRUCT, STRUCT, OFF,
    OFF, OFF, OFF, 2},
    {"getrlimit", UNSIGNED, STRUCT, OFF,
    OFF, OFF, OFF, 2},
    {"getrusage", INT, STRUCT, OFF,
    OFF, OFF, OFF, 2},
    {"sysinfo", STRUCT, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"times", STRUCT, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"ptrace", LONG, LONG, UNSIGNED,
    UNSIGNED, OFF, OFF, 4},
    {"getuid", OFF, OFF, OFF,
    OFF, OFF, OFF, 0},
    {"syslog", INT, CHAR_STAR, INT,
    OFF, OFF, OFF, 3},
    {"getgid", OFF, OFF, OFF,
    OFF, OFF, OFF, 0},
    {"setuid", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"setgid", UNSIGNED, OFF,
    OFF, OFF, OFF, OFF, 1},
    {"geteuid", OFF, OFF, OFF,
    OFF, OFF, OFF, 0},
    {"getegid", OFF, OFF, OFF,
    OFF, OFF, OFF, 0},
    {"setpgid", UNSIGNED, UNSIGNED, OFF,
    OFF, OFF, OFF, 2},
    {"getppid", OFF, OFF, OFF,
    OFF, OFF, OFF,0},
    {"getpgrp", OFF, OFF, OFF,
    OFF, OFF, OFF, 0},
    {"setsid", OFF, OFF, OFF,
    OFF, OFF, OFF,0},
    {"setreuid", UNSIGNED,  UNSIGNED, OFF,
    OFF, OFF, OFF, 2},
    {"setregid", UNSIGNED, UNSIGNED, OFF,
    OFF, OFF, OFF, 2},
    {"getgroups", INT, POINTER, OFF,
    OFF, OFF, OFF,2},
    {"setgroups", INT, UNSIGNED, OFF,
    OFF, OFF, OFF, 2},
    {"setresuid", POINTER, POINTER, POINTER,
    OFF, OFF, OFF, 3},
    {"getresuid", POINTER, POINTER, POINTER,
    OFF, OFF, OFF, 3},
    {"setresgid", UNSIGNED, UNSIGNED, UNSIGNED,
    OFF, OFF, OFF, 3},
    {"getresgid", POINTER, POINTER, POINTER,
    OFF, OFF, OFF, 3},
    {"getpgid", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"setfsuid", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"setfsgid", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"getsid", UNSIGNED, OFF, OFF,
    OFF, OFF, OFF, 1},
    {"capget", STRUCT, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"capset", STRUCT, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"rt_sigpending", UNSIGNED, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"rt_sigtimedwait", POINTER, POINTER, STRUCT, UNSIGNED, OFF, OFF, 4},
    {"rt_sigqueueinfo", UNSIGNED, INT, POINTER, OFF, OFF, OFF, 3},
    {"rt_sigsuspend", POINTER, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"sigaltstack", POINTER, POINTER, OFF, OFF, OFF, OFF, 2},
    {"utime", CHAR_STAR, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"mknod", CHAR_STAR, UNSIGNED, UNSIGNED, OFF, OFF, OFF, 3},
    {"uselib", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"personality", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"ustat", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"statfs", CHAR_STAR, STRUCT, OFF, OFF, OFF, OFF,2},
    {"fstatfs", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"sysfs", INT, UNSIGNED_L, UNSIGNED_L, OFF, OFF, OFF, 3},
    {"getpriority", INT, INT, OFF, OFF, OFF, OFF, 2},
    {"setpriority", INT, INT, INT, OFF, OFF, OFF, 3},
    {"sched_setparam", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"sched_getparam", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"sched_setscheduler", INT, INT, STRUCT, OFF, OFF, OFF, 3},
    {"sched_getscheduler", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"sched_get_priority_max", INT, OFF, OFF, OFF, OFF, OFF, 1},
    {"sched_get_priority_min", INT, OFF, OFF, OFF, OFF, OFF, 1},
    {"sched_rr_get_interval", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"mlock", UNSIGNED_L, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"munlock", UNSIGNED_L, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"mlockall", INT, OFF, OFF, OFF, OFF, OFF, 1},
    {"munlockall", OFF, OFF, OFF, OFF, OFF, OFF, 0},
    {"vhangup", OFF, OFF, OFF, OFF, OFF, OFF, 0},
    {"modify_ldt", INT, POINTER, UNSIGNED_L, OFF, OFF, OFF, 3},
    {"pivot_root", CHAR_STAR, CHAR_STAR, OFF, OFF, OFF, OFF, 2},
    {"_sysctl", STRUCT, OFF, OFF, OFF, OFF, OFF, 1},
    {"prctl", INT, UNSIGNED_L, UNSIGNED_L, UNSIGNED_L, OFF, UNSIGNED, 5},
    {"arch_prctl", STRUCT, INT, UNSIGNED_L, OFF, OFF, OFF, 3},
    {"adjtimex", STRUCT, OFF, OFF, OFF, OFF, OFF, 1},
    {"setrlimit", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"chroot", CHAR_STAR, OFF, OFF, OFF, OFF, OFF, 1},
    {"sync", OFF, OFF, OFF, OFF, OFF, OFF, 0},
    {"acct", CHAR_STAR, OFF, OFF, OFF, OFF, OFF, 1},
    {"settimeofday", STRUCT, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"mount", CHAR_STAR, CHAR_STAR, CHAR_STAR, UNSIGNED, POINTER, OFF, 5},
    {"umount2", CHAR_STAR, INT, OFF, OFF, OFF, OFF, 2},
    {"swapon", CHAR_STAR, INT, OFF, OFF, OFF, OFF, 2},
    {"swapoff", CHAR_STAR, OFF, OFF, OFF, OFF, OFF, 1},
    {"reboot", INT, INT , UNSIGNED, POINTER, OFF, OFF,4},
    {"sethostname", CHAR_STAR, INT, OFF, OFF, OFF, OFF, 2},
    {"setdomainname", CHAR_STAR, INT, OFF, OFF, OFF, OFF, 2},
    {"iopl", UNSIGNED_L, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"ioperm", UNSIGNED, UNSIGNED, INT, OFF, OFF, OFF, 3},
    {"create_module", UNSIGNED_L, UNSIGNED_L, OFF, OFF, OFF, OFF, 2},
    {"init_module", POINTER, UNSIGNED_L, CHAR_STAR, OFF, OFF, OFF, 3},
    {"delete_module", CHAR_STAR, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"get_kernel_syms", OFF, OFF, OFF, OFF, OFF, OFF, 1},
    {"query_module", UNSIGNED, UNSIGNED, UNSIGNED,
    UNSIGNED, UNSIGNED, OFF, 5},
    {"quotactl", UNSIGNED, CHAR_STAR, UNSIGNED, POINTER, OFF, OFF, 4},
    {"nfsservctl", UNSIGNED, UNSIGNED, UNSIGNED, OFF, OFF, OFF, 3},
    {"getpmsg", UNSIGNED, UNSIGNED, UNSIGNED, UNSIGNED,
    UNSIGNED, OFF, 5},
    {"putpmsg", UNSIGNED, UNSIGNED, UNSIGNED,
    UNSIGNED, UNSIGNED, OFF, 5},
    {"afs_syscall", UNSIGNED, UNSIGNED, UNSIGNED,
    UNSIGNED, UNSIGNED, OFF,5},
    {"tuxcall", UNSIGNED, UNSIGNED, UNSIGNED, OFF, OFF, OFF, 3},
    {"security", UNSIGNED, UNSIGNED, UNSIGNED, OFF, OFF, OFF, 3},
    {"gettid", OFF, OFF, OFF, OFF, OFF, OFF, 0},
    {"readahead", INT, UNSIGNED, UNSIGNED, OFF, OFF, OFF, 3},
    {"setxattr", CHAR_STAR, CHAR_STAR, POINTER, UNSIGNED, INT, OFF, 5},
    {"lsetxattr", CHAR_STAR, CHAR_STAR, POINTER, UNSIGNED,INT, OFF, 5},
    {"fsetxattr", INT, CHAR_STAR, POINTER, UNSIGNED, INT, OFF, 5},
    {"getxattr", CHAR_STAR, CHAR_STAR, POINTER, UNSIGNED, OFF, OFF, 4},
    {"lgetxattr", CHAR_STAR, CHAR_STAR, POINTER, UNSIGNED, OFF, OFF, 4},
    {"fgetxattr", INT, CHAR_STAR, POINTER, UNSIGNED, OFF, OFF,4},
    {"listxattr", CHAR_STAR, CHAR_STAR, UNSIGNED, OFF, OFF, OFF, 3},
    {"llistxattr", CHAR_STAR, CHAR_STAR, UNSIGNED, OFF, OFF, OFF, 3},
    {"flistxattr", INT, CHAR_STAR, UNSIGNED, OFF, OFF, OFF, 3},
    {"removexattr", CHAR_STAR, CHAR_STAR,OFF, OFF, OFF, OFF, 2},
    {"lremovexattr", CHAR_STAR, CHAR_STAR, OFF, OFF, OFF, OFF, 2},
    {"fremovexattr", INT, CHAR_STAR, OFF, OFF, OFF, OFF,2},
    {"tkill", UNSIGNED, INT, OFF, OFF, OFF, OFF,2},
    {"time", POINTER, OFF, OFF, OFF, OFF, OFF, 1},
    {"futex", POINTER, INT , UNSIGNED, STRUCT,POINTER, UNSIGNED, 6},
    {"sched_setaffinity", UNSIGNED, UNSIGNED, POINTER, OFF, OFF, OFF, 3},
    {"sched_getaffinity", UNSIGNED, UNSIGNED, POINTER, OFF, OFF, OFF, 3},
    {"set_thread_area", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"io_setup", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"io_destroy", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"io_getevents", POINTER, LONG, LONG, STRUCT, OFF, OFF, 4},
    {"io_submit", POINTER, LONG, STRUCT, OFF, OFF, OFF, 3},
    {"io_cancel", POINTER, STRUCT, STRUCT, OFF, OFF, OFF, 3},
    {"get_thread_area", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"lookup_dcookie", UNSIGNED, LONG, LONG, OFF, OFF, OFF, 3},
    {"epoll_create", INT, OFF, OFF, OFF, OFF, OFF, 1},
    {"epoll_ctl_old", UNSIGNED, UNSIGNED, UNSIGNED,
    UNSIGNED, OFF, OFF, 4},
    {"epoll_wait_old", UNSIGNED, UNSIGNED, UNSIGNED,
    UNSIGNED, OFF, OFF, 4},
    {"remap_file_pages", UNSIGNED_L, UNSIGNED_L, UNSIGNED_L,
    UNSIGNED_L, UNSIGNED_L, OFF, 5},
    {"getdents64", UNSIGNED, STRUCT, UNSIGNED, OFF, OFF, OFF, 3},
    {"set_tid_address", POINTER, OFF, OFF, OFF, OFF, OFF, 1},
    {"restart_syscall", OFF, OFF, OFF, OFF, OFF, OFF, 0},
    {"semtimedop", INT, STRUCT,UNSIGNED,STRUCT, OFF, OFF, 4},
    {"fadvise64", INT ,UNSIGNED, UNSIGNED, INT, OFF, OFF, 4},
    {"timer_create", UNSIGNED, STRUCT, POINTER, OFF, OFF, OFF, 3},
    {"timer_settime", UNSIGNED, INT, STRUCT, STRUCT, OFF, OFF, 4},
    {"timer_gettime", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"timer_getoverrun", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"timer_delete", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"clock_settime", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"clock_gettime", UNSIGNED,  STRUCT, OFF, OFF, OFF, OFF, 2},
    {"clock_getres", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"clock_nanosleep", UNSIGNED, INT, STRUCT, STRUCT, OFF, OFF, 4},
    {"exit_group", INT, OFF, OFF, OFF, OFF, OFF, 1},
    {"epoll_wait", INT, STRUCT, INT , INT, OFF, OFF, 4},
    {"epoll_ctl", INT, INT, INT, STRUCT, OFF, OFF, 4},
    {"tgkill", UNSIGNED, UNSIGNED, INT, OFF, OFF, OFF, 3},
    {"utimes", CHAR_STAR, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"vserver", UNSIGNED, UNSIGNED, UNSIGNED, UNSIGNED, UNSIGNED, OFF, 5},
    {"mbind", UNSIGNED, UNSIGNED, UNSIGNED_L, POINTER,
    UNSIGNED_L, UNSIGNED, 6},
    {"set_mempolicy", POINTER, UNSIGNED_L, UNSIGNED_L, OFF, OFF, OFF, 3},
    {"get_mempolicy", POINTER, POINTER, UNSIGNED_L,
    UNSIGNED_L, UNSIGNED_L, OFF, 5},
    {"mq_open", CHAR_STAR, INT, UNSIGNED, STRUCT, OFF, OFF, 4},
    {"mq_unlink", CHAR_STAR, OFF, OFF, OFF, OFF, OFF, 1},
    {"mq_timedsend", UNSIGNED, CHAR_STAR,
    UNSIGNED, UNSIGNED, STRUCT, OFF, 5},
    {"mq_timedreceive", UNSIGNED, CHAR_STAR, UNSIGNED,
    UNSIGNED, STRUCT, OFF, 5},
    {"mq_notify", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"mq_getsetattr", UNSIGNED, STRUCT, STRUCT, OFF, OFF, OFF, 3},
    {"kexec_load", UNSIGNED_L, UNSIGNED_L, STRUCT,
    UNSIGNED_L, OFF, OFF, 4},
    {"waitid", INT, UNSIGNED, STRUCT, INT, STRUCT, OFF, 5},
    {"add_key", CHAR_STAR, CHAR_STAR, CHAR_STAR, UNSIGNED, OFF, OFF, 4},
    {"request_key", CHAR_STAR, CHAR_STAR, CHAR_STAR, UNSIGNED, OFF, OFF, 4},
    {"keyctl", INT, UNSIGNED_L, UNSIGNED_L, UNSIGNED_L,
    UNSIGNED_L, OFF, 5},
    {"ioprio_set", INT, INT, INT, OFF, OFF, OFF, 3},
    {"ioprio_get", INT, INT, OFF, OFF, OFF, OFF, 2},
    {"inotify_init", OFF, OFF, OFF, OFF, OFF, OFF, 0},
    {"inotify_add_watch", INT, CHAR_STAR, UNSIGNED, OFF, OFF, OFF, 3},
    {"inotify_rm_watch", INT, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"migrate_pages", UNSIGNED, UNSIGNED_L, POINTER, POINTER,
    OFF, OFF, 4},
    {"openat", INT, CHAR_STAR, INT, INT, OFF, OFF, 4},
    {"mkdirat", INT, CHAR_STAR, INT, OFF, OFF, OFF, 3},
    {"mknodat", INT, CHAR_STAR, INT, UNSIGNED, OFF, OFF, 4},
    {"fchownat", INT, CHAR_STAR, UNSIGNED, UNSIGNED, INT, OFF, 5},
    {"futimesat", INT, CHAR_STAR, STRUCT, OFF, OFF, OFF, 3},
    {"newfstatat", INT, CHAR_STAR, STRUCT, INT, OFF, OFF, 4},
    {"unlinkat", INT, CHAR_STAR, INT, OFF, OFF, OFF, 3},
    {"renameat", INT, CHAR_STAR, INT, CHAR_STAR, OFF, OFF, 4},
    {"linkat", INT, CHAR_STAR, INT, CHAR_STAR, INT, OFF, 5},
    {"symlinkat", CHAR_STAR, INT, CHAR_STAR, OFF, OFF, OFF, 3},
    {"readlinkat", INT, CHAR_STAR, CHAR_STAR, INT, OFF, OFF, 4},
    {"fchmodat", INT, CHAR_STAR, UNSIGNED, OFF, OFF, OFF, 3},
    {"faccessat", INT, CHAR_STAR, UNSIGNED, OFF, OFF, OFF, 3},
    {"pselect6", INT, POINTER, POINTER, POINTER, STRUCT, POINTER, 6},
    {"ppoll", STRUCT, UNSIGNED, STRUCT, POINTER, UNSIGNED, OFF, 5},
    {"unshare", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"set_robust_list", STRUCT, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"get_robust_list", INT, STRUCT, POINTER, OFF, OFF, OFF, 3},
    {"splice", INT, POINTER, INT, POINTER, UNSIGNED, UNSIGNED, 6},
    {"tee", INT, INT, UNSIGNED, UNSIGNED, OFF, OFF, 4},
    {"sync_file_range", LONG, UNSIGNED, UNSIGNED, LONG, OFF, OFF, 4},
    {"vmsplice", INT, STRUCT, UNSIGNED_L, UNSIGNED, OFF, OFF, 4},
    {"move_pages", UNSIGNED, UNSIGNED_L,
    POINTER_P, POINTER, POINTER, INT, 6},
    {"utimensat", INT, CHAR_STAR, STRUCT, INT, OFF, OFF, 4},
    {"epoll_pwait", INT, STRUCT, INT, INT, POINTER, UNSIGNED, 6},
    {"signalfd", INT, POINTER, UNSIGNED, OFF, OFF, OFF, 3},
    {"timerfd_create", INT, INT, OFF, OFF, OFF, OFF, 2},
    {"eventfd", UNSIGNED, OFF, OFF, OFF, OFF, OFF, 1},
    {"fallocate", LONG, LONG, UNSIGNED, UNSIGNED, OFF, OFF, 4},
    {"timerfd_settime", INT, INT, STRUCT, STRUCT, OFF, OFF, 4},
    {"timerfd_gettime", INT, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"accept4", INT, STRUCT, POINTER, INT, OFF, OFF, 4},
    {"signalfd4", INT,STRUCT, INT, INT, OFF, OFF, 4},
    {"eventfd2", UNSIGNED, INT, OFF, OFF, OFF, OFF, 2},
    {"epoll_create1", INT, OFF, OFF, OFF, OFF, OFF,1},
    {"dup3", UNSIGNED, UNSIGNED, INT, OFF, OFF, OFF, 3},
    {"pipe2", POINTER, INT, OFF, OFF, OFF, OFF, 2},
    {"inotify_init1", INT, OFF, OFF, OFF, OFF, OFF, 1},
    {"preadv", UNSIGNED_L, STRUCT, UNSIGNED_L,
    UNSIGNED_L, UNSIGNED_L, OFF, 5},
    {"pwritev", UNSIGNED_L, STRUCT, UNSIGNED_L,
    UNSIGNED_L, UNSIGNED_L, OFF, 5},
    {"rt_tgsigqueueinfo", UNSIGNED, UNSIGNED, INT, POINTER, OFF, OFF, 4},
    {"perf_event_open", STRUCT, UNSIGNED, INT, INT, UNSIGNED_L, OFF, 5},
    {"recvmmsg", INT, STRUCT, UNSIGNED, UNSIGNED, STRUCT, OFF, 5},
    {"fanotify_init", UNSIGNED, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"fanotify_mark", LONG, LONG, UNSIGNED, LONG, LONG, OFF, 5},
    {"prlimit64", UNSIGNED, UNSIGNED, STRUCT, STRUCT, OFF, OFF, 4},
    {"name_to_handle_at", INT, CHAR_STAR, STRUCT, POINTER, INT, OFF, 5},
    {"open_by_handle_at", INT, CHAR_STAR, STRUCT, POINTER, INT, OFF, 5},
    {"clock_adjtime", UNSIGNED, STRUCT, OFF, OFF, OFF, OFF, 2},
    {"syncfs", INT, OFF, OFF, OFF, OFF, OFF, 1},
    {"sendmmsg", INT, STRUCT, UNSIGNED, UNSIGNED, OFF, OFF, 4},
    {"setns", INT, INT, OFF, OFF, OFF, OFF, 2},
    {"getcpu", POINTER, POINTER, STRUCT, OFF, OFF, OFF, 3},
    {"process_vm_readv", UNSIGNED, STRUCT, UNSIGNED_L,
    STRUCT, UNSIGNED_L, UNSIGNED_L, 6},
    {"process_vm_writev", UNSIGNED, STRUCT, UNSIGNED_L,
    STRUCT, UNSIGNED_L, UNSIGNED_L, 6},
    {"kcmp", UNSIGNED, UNSIGNED, INT, UNSIGNED_L, UNSIGNED_L, OFF, 5},
    {"finit_module", INT, CHAR_STAR, INT, OFF, OFF, OFF, 3},
    {"sched_setattr", UNSIGNED, STRUCT, UNSIGNED, OFF, OFF, OFF, 3},
    {"sched_getattr", UNSIGNED, STRUCT, UNSIGNED, UNSIGNED, OFF, OFF, 4},
    {"renameat2", INT, CHAR_STAR, INT, CHAR_STAR, UNSIGNED, OFF, 5},
    {"seccomp", UNSIGNED, UNSIGNED, CHAR_STAR, OFF, OFF, OFF, 3},
    {"getrandom", CHAR_STAR, UNSIGNED, UNSIGNED, OFF, OFF, OFF, 3},
    {"memfd_create", CHAR_STAR, UNSIGNED, OFF, OFF, OFF, OFF, 2},
    {"kexec_file_load", INT, INT, UNSIGNED_L,
    CHAR_STAR, UNSIGNED_L, OFF, 5},
    {"bpf", INT, POINTER, UNSIGNED, OFF, OFF, OFF, 3},
    {"execveat", INT, CHAR_STAR, POINTER, POINTER, INT, OFF, 5},
    {"userfaultfd", INT, OFF, OFF, OFF, OFF, OFF, 1},
    {"membarrier", INT, INT, OFF, OFF, OFF, OFF, 2},
    {"mlock2", UNSIGNED_L, UNSIGNED, INT, OFF, OFF, OFF, 3},
    {"copy_file_range", INT, POINTER, INT,
    POINTER, UNSIGNED, UNSIGNED, 6},
    {"preadv2", UNSIGNED_L, STRUCT, UNSIGNED_L,
    UNSIGNED_L, UNSIGNED_L ,INT, 6},
    {"pwritev2", UNSIGNED_L, STRUCT, UNSIGNED_L,
    UNSIGNED_L, UNSIGNED_L, INT,6},
};

#endif /* !SYSCALL_INFO_H_ */